# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
exclude: [vendor]

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: transitioningcw # jekyll-seo-tag > Owners twitter username
author: Transitioning # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Transitioning to College Writing # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/transitioningcw
    - https://www.facebook.com/TransitioningToCollegeWriting

# 4. Jekyll settings
sass:
style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Central/Chicago # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Symposium Blog" # The post list page content
    feature_text: 
    feature_image: 

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: 
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: 

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Transitioning to College Writing" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/trans2.png" # Site logo, also used in jekyll-seo-tag
description: "Each year, the Department of Writing and Rhetoric, along with other UM partners, hosts a themed Transitioning to College Writing Symposium in support of writing instruction in our area." # Site description and default description, also used in jekyll-seo-tag
url: "http://transitioning.olemiss.edu" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/adavis46/tcw"
email: "transitioning@olemiss.edu"
disqus: ""
avatarurl: "/assets/trans2.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  Call for Proposals: /cfp/
  Program: /program/
  Registration: /register/
  Travel and Grants: /travel/ 
  
navigation_footer:
  Department of Writing and Rhetoric: http://rhetoric.olemiss.edu
  University of Mississippi: http://www.olemiss.edu 
  Site Based on Alembic: https://alembic.darn.es/

social_links:
  Twitter: "https://twitter.com/transitioningcw"
  Facebook: "https://www.facebook.com/TransitioningToCollegeWriting"

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ""

# 9. Google Services
google_analytics: UA-508224-1
